onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group Testbench
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/sys_clock
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/sys_reset
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_clock
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_reset
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/wishbone_stb
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/wishbone_sel
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/wishbone_we
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/wishbone_ack
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/wishbone_err
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/wishbone_cyc
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/wishbone_adr
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/wishbone_dat_w
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/wishbone_dat_r
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/sink_valid
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/sink_ready
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/sink_data
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/source_valid
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/source_ready
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/source_data
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_clk
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_rst
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_fdct_fifo_rd
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/encoder_fdct_fifo_q
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_fdct_fifo_hf_full
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_output_fifo_almost_full
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_output_fifo_sink_valid
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/encoder_output_fifo_sink_payload_data
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/encoder_jpeg_bus_dat_w
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/encoder_jpeg_bus_dat_r
add wave -noupdate -group Testbench -format Literal -radix hexadecimal /tb_core/core/encoder_jpeg_bus_sel
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_jpeg_bus_ack
add wave -noupdate -group Testbench -format Logic -radix hexadecimal /tb_core/core/encoder_jpeg_bus_err
add wave -noupdate -group JpegEnc
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/clk
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/rst
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/opb_abus
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/opb_be
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/opb_dbus_in
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/opb_rnw
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/opb_select
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/opb_dbus_out
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/opb_xferack
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/opb_retry
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/opb_toutsup
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/opb_errack
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/fdct_fifo_rd
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/fdct_fifo_q
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/fdct_fifo_hf_full
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/fdct_fifo_dval_o
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/ram_byte
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/ram_wren
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/ram_wraddr
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/outif_almost_full
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/frame_size
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/qdata
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/qaddr
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/qwren
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/jpeg_ready
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/jpeg_busy
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/outram_base_addr
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/num_enc_bytes
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/img_size_x
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/img_size_y
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/sof
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/jpg_iram_rden
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/jpg_iram_rdaddr
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/jpg_iram_rdata
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/fdct_start
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/fdct_ready
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/zig_start
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/zig_ready
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/qua_start
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/qua_ready
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/rle_start
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/rle_ready
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/huf_start
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/huf_ready
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/bs_start
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/bs_ready
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/zz_buf_sel
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/zz_rd_addr
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/zz_data
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/rle_buf_sel
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/rle_rdaddr
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/rle_data
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/qua_buf_sel
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/qua_rdaddr
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/qua_data
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/huf_buf_sel
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/huf_rdaddr
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/huf_rden
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/huf_runlength
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/huf_size
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/huf_amplitude
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/huf_dval
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/bs_buf_sel
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/bs_fifo_empty
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/bs_rd_req
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/bs_packed_byte
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/huf_fifo_empty
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/zz_rden
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/fdct_sm_settings
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/zig_sm_settings
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/qua_sm_settings
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/rle_sm_settings
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/huf_sm_settings
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/bs_sm_settings
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/image_size_reg
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/jfif_ram_byte
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/jfif_ram_wren
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/jfif_ram_wraddr
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/out_mux_ctrl
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/img_size_wr
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/jfif_start
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/jfif_ready
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/bs_ram_byte
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/bs_ram_wren
add wave -noupdate -group JpegEnc -format Literal -radix hexadecimal /tb_core/core/JpegEnc/bs_ram_wraddr
add wave -noupdate -group JpegEnc -format Logic -radix hexadecimal /tb_core/core/JpegEnc/jfif_eoi
add wave -noupdate -group FDCT
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/clk
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/rst
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/start_pb
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/ready_pb
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fdct_sm_settings
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_fifo_rd
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_fifo_q
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_fifo_hf_full
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_fifo_dval_o
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/zz_buf_sel
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/zz_rd_addr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/zz_data
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/zz_rden
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/img_size_x
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/img_size_y
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/sof
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/mdct_data_in
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/mdct_idval
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/mdct_odval
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/mdct_data_out
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/odv1
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/dcto1
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/x_pixel_cnt
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/y_line_cnt
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/rd_addr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/input_rd_cnt
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/rd_en
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/rd_en_d1
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/rdaddr
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_dval
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_dval_m1
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_dval_m2
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_dval_m3
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/wr_cnt
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/dbuf_data
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/dbuf_q
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/dbuf_we
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/dbuf_waddr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/dbuf_raddr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/xw_cnt
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/yw_cnt
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/dbuf_q_z1
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/sim_rd_addr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/y_8bit
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cb_8bit
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cr_8bit
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cmp_idx
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d1
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d2
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d3
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d4
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d5
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d6
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d7
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/cur_cmp_idx_d8
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_rd
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_wr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_q
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_full
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_empty
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_count
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_rd_cnt
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo1_q_dval
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo_data_in
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fifo_rd_arm
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/eoi_fdct
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/bf_fifo_rd_s
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/start_int
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/start_int_d
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_data
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_q
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_we
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_waddr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_raddr
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_rd_d
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_rd
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/rd_started
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/writing_en
add wave -noupdate -group FDCT -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_q_vld
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_line_cnt
add wave -noupdate -group FDCT -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_fdct/fram1_pix_cnt
add wave -noupdate -group ZZTop
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/clk
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/rst
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/start_pb
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/ready_pb
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/zig_sm_settings
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/qua_buf_sel
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/qua_rdaddr
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/qua_data
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/fdct_buf_sel
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/fdct_rd_addr
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/fdct_data
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/fdct_rden
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/dbuf_data
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/dbuf_q
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/dbuf_we
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/dbuf_waddr
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/dbuf_raddr
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/zigzag_di
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/zigzag_divalid
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/zigzag_dout
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/zigzag_dovalid
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/wr_cnt
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/rd_cnt
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/rd_en_d
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/rd_en
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/fdct_buf_sel_s
add wave -noupdate -group ZZTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/zz_rd_addr
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/fifo_empty
add wave -noupdate -group ZZTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_zz_top/fifo_rden
add wave -noupdate -group QwantTop
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/clk
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/rst
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/start_pb
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/ready_pb
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/qua_sm_settings
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/rle_buf_sel
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/rle_rdaddr
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/rle_data
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/zig_buf_sel
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/zig_rd_addr
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/zig_data
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/qdata
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/qaddr
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/qwren
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/dbuf_data
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/dbuf_q
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/dbuf_we
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/dbuf_waddr
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/dbuf_raddr
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/zigzag_di
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/zigzag_divalid
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/quant_dout
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/quant_dovalid
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/wr_cnt
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/rd_cnt
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/rd_en_d
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/rd_en
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/zig_buf_sel_s
add wave -noupdate -group QwantTop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/zz_rd_addr
add wave -noupdate -group QwantTop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_quant_top/fifo_empty
add wave -noupdate -group RLETop
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/clk
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rst
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/start_pb
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/ready_pb
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rle_sm_settings
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_buf_sel
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_rden
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_runlength
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_size
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_amplitude
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_dval
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_fifo_empty
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/qua_buf_sel
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/qua_rd_addr
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/qua_data
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/sof
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/dbuf_data
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/dbuf_q
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/dbuf_we
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rle_runlength
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rle_size
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rle_amplitude
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rle_dovalid
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rle_di
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/rle_divalid
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/qua_buf_sel_s
add wave -noupdate -group RLETop -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/huf_dval_p0
add wave -noupdate -group RLETop -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_rle_top/wr_cnt
add wave -noupdate -group Huffman
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/clk
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/rst
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/start_pb
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/ready_pb
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/huf_sm_settings
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/sof
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/img_size_x
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/img_size_y
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/rle_buf_sel
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/rd_en
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/runlength
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_size
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/d_val
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/rle_fifo_empty
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/bs_buf_sel
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/bs_fifo_empty
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/bs_rd_req
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/bs_packed_byte
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/state
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/rle_buf_sel_s
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/first_rle_word
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/word_reg
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/bit_ptr
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/num_fifo_wrs
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_ext
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_ext_size
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/ready_hfw
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/fifo_wbyte
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/fifo_wrt_cnt
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/fifo_wren
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/last_block
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/image_area_size
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/block_cnt
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_size
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_dc_size
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_dc
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_ac_size
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_ac
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_vld
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/d_val_d1
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/d_val_d2
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/d_val_d3
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/d_val_d4
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_size_d
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_d
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_size_d1
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_d1
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/hfw_running
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/runlength_r
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_size_r
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vli_r
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/rd_en_s
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/pad_byte
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/pad_reg
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_cr_dc_size
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_cr_dc
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_cr_ac_size
add wave -noupdate -group Huffman -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/vlc_cr_ac
add wave -noupdate -group Huffman -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/start_pb_d1
add wave -noupdate -group ByteStuffer
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/clk
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/rst
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/start_pb
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/ready_pb
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/sof
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/num_enc_bytes
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/outram_base_addr
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/huf_buf_sel
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/huf_fifo_empty
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/huf_rd_req
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/huf_packed_byte
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/ram_byte
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/ram_wren
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/ram_wraddr
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/huf_data_val
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/wdata_reg
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/wraddr
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/wr_n_cnt
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/huf_buf_sel_s
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/rd_en
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/rd_en_d1
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/huf_rd_req_s
add wave -noupdate -group ByteStuffer -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/latch_byte
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/data_valid
add wave -noupdate -group ByteStuffer -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_bytestuffer/wait_for_ndata
add wave -noupdate -group HuffmanDoubleFIFO
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/clk
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/rst
add wave -noupdate -group HuffmanDoubleFIFO -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/data_in
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/wren
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/buf_sel
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/rd_req
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo_empty
add wave -noupdate -group HuffmanDoubleFIFO -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/data_out
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo1_rd
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo1_wr
add wave -noupdate -group HuffmanDoubleFIFO -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo1_q
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo1_full
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo1_empty
add wave -noupdate -group HuffmanDoubleFIFO -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo1_count
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo2_rd
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo2_wr
add wave -noupdate -group HuffmanDoubleFIFO -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo2_q
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo2_full
add wave -noupdate -group HuffmanDoubleFIFO -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo2_empty
add wave -noupdate -group HuffmanDoubleFIFO -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo2_count
add wave -noupdate -group HuffmanDoubleFIFO -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/fifo_data_in
add wave -noupdate -group HuffmanFIFO1
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/rst
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/clk
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/rinc
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/winc
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/datai
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/datao
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/fullo
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/emptyo
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/count
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/raddr_reg
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/waddr_reg
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/count_reg
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/rd_en_reg
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/wr_en_reg
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/empty_reg
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/full_reg
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/ramq
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/ramd
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/ramwaddr
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/ramenw
add wave -noupdate -group HuffmanFIFO1 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/ramraddr
add wave -noupdate -group HuffmanFIFO1 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_1/ramenr
add wave -noupdate -group HuffmanFIFO2
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/rst
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/clk
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/rinc
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/winc
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/datai
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/datao
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/fullo
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/emptyo
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/count
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/raddr_reg
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/waddr_reg
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/count_reg
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/rd_en_reg
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/wr_en_reg
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/empty_reg
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/full_reg
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/ramq
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/ramd
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/ramwaddr
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/ramenw
add wave -noupdate -group HuffmanFIFO2 -format Literal -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/ramraddr
add wave -noupdate -group HuffmanFIFO2 -format Logic -radix hexadecimal /tb_core/core/JpegEnc/u_huffman/u_doublefifo/u_fifo_2/ramenr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {100830 ps} 0}
configure wave -namecolwidth 380
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1973684 ps}
